Public Class host
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Process.Start("CMD", "/C echo 127.0.0.1 vortex.data.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 vortex-win.data.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 telecommand.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 oca.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 oca.telemetry.microsoft.com.nsatc.net >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 sqm.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 sqm.telemetry.microsoft.com.nsatc.net >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 watson.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 watson.telemetry.microsoft.com.nsatc.net >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 redir.metaservices.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 choice.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 choice.microsoft.com.nsatc.net >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 df.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 reports.wes.df.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 services.wes.df.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 sqm.df.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 watson.ppe.telemetry.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 telemetry.appex.bing.net >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 telemetry.urs.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 telemetry.appex.bing.net:443 >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 settings-sandbox.data.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 vortex-sandbox.data.microsoft.com >> %windir%\System32\drivers\etc\hosts")
        Process.Start("CMD", "/C echo 127.0.0.1 telemetry >> %windir%\System32\drivers\etc\hosts")
        MsgBox("FINISHED")
        Close()
    End Sub
End Class